### ISSUE TITLE
Create an Order

### ISSUE THREAD

**Issue by divyanshusharma1709** [CSCI-GA-2820-SU24-001/orders#1]
**As an** Orders Manager
**I need** to create an order item 
**So that** orders can be created and processed
   
 ### Details and Assumptions
 * The IDs of the products in the order are provided 
 * The quantity of each item in the order is provided
 * The price of each item and the customer ID is provided
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given the items and their quantities in an order
 When an order is placed
 Then order item created and stored in the database
```

**Comment by ziyuzoo** [comment]
I think we're missing price in the order?

**Comment by ziyuzoo** [comment]
customer id as well

**Comment by yl12065** [comment]
If we consider the authentication process, is it a separate section that includes customer/manager login, customer registration, and verification? It seems to be related to the Customers Squad.

**Comment by divyanshusharma1709** [comment]
@ziyuzoo Thanks for the heads up! I have updated it.
@yl12065 I think that we can assume that the API can only be called by authenticated users
