### ISSUE TITLE
Delete Item from Order

### ISSUE THREAD

**Issue by yl12065** [CSCI-GA-2820-SU24-001/orders#10]
**As a** Customer
**I need** to remove the order item from my order
**So that** I can remove the item that I do not need anymore
   
 ### Details and Assumptions
 * The Order ID is provided
 * Relevant authorization by the Customer is valid, and Customer ID is provided
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given Order ID 
 When the Customer chooses to remove the order item
 Then this item is removed from the Order
```

**Comment by divyanshusharma1709** [comment]
We should also include the item ID to be removed from the order

**Comment by divyanshusharma1709** [comment]
Completed by #24
