### ISSUE TITLE
Service information endpoint 

### ISSUE THREAD

**Issue by ziyuzoo** [CSCI-GA-2820-SU24-001/orders#12]
As a developer
I need to provide information about the service and its exposed API endpoints at the root URL
So that users and developers can easily understand the service capabilities and available endpoints

Details 
update the base URL to return information about the service as json

Acceptance Criteria
Given a running service
When a request is made to the root URL `/`
Then a JSON response is returned with information about the service and its exposed API endpoints

**Comment by divyanshusharma1709** [comment]
We could do this at the end of development when we know all the API endpoints
