### ISSUE TITLE
Read a single Item from an Order

### ISSUE THREAD

**Issue by ziyuzoo** [CSCI-GA-2820-SU24-001/orders#13]
**As a** user
**I need** to read any given item in an order 
**So that** I can read full order detail
   
 ### Details and Assumptions
 * return detail information on the order item 
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given a order and items in the order
 When the caller calls GET /order/<order_id>/item/<item_id>
 Then the response is a 201
 And response json contains detail on the item 
```

**Comment by divyanshusharma1709** [comment]
Closed by #22
