### ISSUE TITLE
Query Resources by Customer ID

### ISSUE THREAD

**Issue by yw8077** [CSCI-GA-2820-SU24-001/orders#35]
**As a** developer
**I need** to query orders by customer ID
**So that** I can retrieve orders from the same customer
   
 ### Details and Assumptions
 * The API should return a list of orders that match the query criteria.
   
 ### Acceptance Criteria  
   
 ```gherkin
 When I query orders by customer ID
 It should return a list of orders that match the customer ID
```

**Comment by ziyuzoo** [comment]
maybe im missing something - this reads very similar to (subset of) #36, as in customer id could be a filter criteria for the query endpoint?

**Comment by yw8077** [comment]
this one is applied to view_order specifically, and #36 is more general, including view_item and list_items_in_order, which we may need to address what requirements we might need
