### ISSUE TITLE
Update  an order

### ISSUE THREAD

**Issue by saikkc007** [CSCI-GA-2820-SU24-001/orders#5]
As a customer/orders manager, 
I need to modify an order before it ships 

The user should be able to modify an order as long as its status is still "placed".
Modifying an order should update the order accordingly.

### Details and Assumptions
- The order ID is provided
- Relevant authorization by the customer/admin is checked and approved
- Outline the process for updating the order if payment has already been made (e.g., partial refund, additional charge).

### Acceptance criteria:
```javascript
Given an ORDER ID
When a MODIFY ORDER request is made
Then the order is modified if order status is "Placed"
```

**Comment by ziyuzoo** [comment]
i would argue for MVP let's only add the ability to delete order in placed status (not completed) and keep it simple

**Comment by saikkc007** [comment]
But prof told to add it ?

**Comment by ziyuzoo** [comment]
sorry where is this requirement? (i could be missing info somewhere, thanks!)
