### ISSUE TITLE
Service README

### ISSUE THREAD

**Issue by ziyuzoo** [CSCI-GA-2820-SU24-001/orders#7]
**As a** developer
**I need** container set up for the project
**So that** I can write more functionality 
   
 ### Details and Assumptions
 * update the README.md file with information about the order service
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given a repo containing app setup 
 When someone opens the repo
 Then they can build and run test locally based on instructions in the README
```

**Comment by yl12065** [comment]
I suggest this issue and the database one could be labeled as "technical debt" according to the Sprint 0 Execute requirement. 
Since I did not see anywhere to change the label, we might need to choose the Maintainer of the GitHub repository first, and then we can make this label change.
